### ISSUE TITLE
Type for "status" array in wait/test API

### ISSUE THREAD

**Issue by davidozog** [davidozog/openshmem-specification#1]
PR #214 proposes the `status` mask array for the following routines:
- `shmem_wait_until_any` / `shmem_test_any`
- `shmem_wait_until_some` / `shmem_test_some`

The type of `status` needs to hold 0 and 1, but `bool` requires `stdbool.h`, which we're trying to avoid (more discussion in the #214 ticket).

As of now, the type is `int *`, which naturally aligns with the CPU word size, but potentially wastes memory.  We're considering changing this to `char *`, `short *`, or some other type that wastes less memory.

I'm experimenting with a [Github poll](https://github.com/apps/polls) below to take a straw poll.  Please make a selection and let me know if there is an alternative you'd like to add.

[![](https://api.gh-polls.com/poll/01CVX4E6EW3HSZ7MRGA26CJHB5/int)](https://api.gh-polls.com/poll/01CVX4E6EW3HSZ7MRGA26CJHB5/int/vote)
[![](https://api.gh-polls.com/poll/01CVX4E6EW3HSZ7MRGA26CJHB5/char)](https://api.gh-polls.com/poll/01CVX4E6EW3HSZ7MRGA26CJHB5/char/vote)
[![](https://api.gh-polls.com/poll/01CVX4E6EW3HSZ7MRGA26CJHB5/short)](https://api.gh-polls.com/poll/01CVX4E6EW3HSZ7MRGA26CJHB5/short/vote)
[![](https://api.gh-polls.com/poll/01CVX4E6EW3HSZ7MRGA26CJHB5/unsigned%20char)](https://api.gh-polls.com/poll/01CVX4E6EW3HSZ7MRGA26CJHB5/unsigned%20char/vote)
[![](https://api.gh-polls.com/poll/01CVX4E6EW3HSZ7MRGA26CJHB5/bool)](https://api.gh-polls.com/poll/01CVX4E6EW3HSZ7MRGA26CJHB5/bool/vote)
[![](https://api.gh-polls.com/poll/01CVX4E6EW3HSZ7MRGA26CJHB5/anything%20except%20bool)](https://api.gh-polls.com/poll/01CVX4E6EW3HSZ7MRGA26CJHB5/anything%20except%20bool/vote)

**Comment by davidozog** [comment]
+1 if you voted!

**Comment by jdinan** [comment]
Where is the "anything except `bool`" option?  :neckbeard: 

Why this matters to some apps is you may have arrays of length `npes` at each PE and you have `ppn` PEs per node, the memory per node for this array is `npes*ppn*sizeof(...)`.  Does it help users to reduce the size component by a factor of 2 or 4?

**Comment by davidozog** [comment]
@jdinan:  Hah!  I added it.

**Comment by davidozog** [comment]
Closed by https://github.com/openshmem-org/specification/pull/214
